/**
 * Packaging contract: every file the published `exports` map promises must
 * actually land in the npm tarball. v1.0.0 shipped with `src/` but no `types/`
 * — the exports map pointed each subpath at a `./types/*.d.mts` that was never
 * packed, so consumers under `checkJs`/strict resolved the imports to untyped
 * `.mjs` and `tsc` failed. The declarations are generated by the `prepack`
 * lifecycle script (`build:types`) and listed in `files`; drop either and the
 * tarball silently loses its types again.
 *
 * `npm pack --dry-run --json` runs `prepack` exactly as a real publish does and
 * reports the resulting file list, so this asserts against what would actually
 * be shipped rather than the working tree. Each `types`/`default` target in the
 * exports map must appear in that list; the `.d.mts` half is asserted non-empty
 * so the check can never pass vacuously if the type targets disappear.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const repoRoot = execFileSync("git", ["rev-parse", "--show-toplevel"], {
  encoding: "utf8",
}).trim();

const pkg = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);

// The conditions in each exports subpath that name a shipped file. `import`,
// `require`, and `node` would join these if added later; enumerating the live
// set keeps the guard tracking the real map instead of a hard-coded pair.
const FILE_CONDITIONS = ["types", "default", "import", "require", "node"];

function exportedFiles() {
  const types = [];
  const runtime = [];
  for (const target of Object.values(pkg.exports)) {
    for (const [condition, value] of Object.entries(target)) {
      if (!FILE_CONDITIONS.includes(condition)) continue;
      const file = value.replace(/^\.\//, "");
      (condition === "types" ? types : runtime).push(file);
    }
  }
  return { types, runtime };
}

// Pack list as it would publish: `--dry-run` runs `prepack` (building the
// declarations) without writing a tarball; `--json` gives a stable file list.
function packedFiles() {
  const out = execFileSync(
    "npm",
    ["pack", "--dry-run", "--json", "--ignore-scripts=false"],
    { cwd: repoRoot, encoding: "utf8" },
  );
  return new Set(JSON.parse(out)[0].files.map((f) => f.path));
}

describe("packaging contract: exports map vs. published tarball", () => {
  const { types, runtime } = exportedFiles();
  const packed = packedFiles();

  it("ships a declaration for every exports subpath (non-vacuous)", () => {
    assert.ok(
      types.length > 0,
      "no `types` conditions found in exports — the guard would pass vacuously",
    );
    const missing = types.filter((f) => !packed.has(f));
    assert.deepEqual(
      missing,
      [],
      `exports promise .d.mts files the tarball does not ship: ${missing.join(", ")}. ` +
        "Did `prepack`/`build:types` or the `types` entry in `files` get dropped?",
    );
  });

  it("ships the runtime entry for every exports subpath", () => {
    assert.ok(runtime.length > 0, "no runtime conditions found in exports");
    const missing = runtime.filter((f) => !packed.has(f));
    assert.deepEqual(
      missing,
      [],
      `exports promise runtime files the tarball does not ship: ${missing.join(", ")}`,
    );
  });
});
